//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int Id_register { get; set; }
        public int Id_synyp { get; set; }
        public int Id_pan { get; set; }
        public int Id_meml_kyzmetker { get; set; }
        public int Id_mektep { get; set; }
    
        public virtual Mektepter Mektepter { get; set; }
        public virtual Meml_kyzmetker Meml_kyzmetker { get; set; }
        public virtual Pander Pander { get; set; }
        public virtual Synyptar Synyptar { get; set; }
    }
}
