//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sabak_kestesi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sabak_kestesi()
        {
            this.Jurnal = new HashSet<Jurnal>();
        }
    
        public int Id_sabak { get; set; }
        public string Sabak_uakyty { get; set; }
        public string Sabak_aty { get; set; }
        public int Id_Ata_ana { get; set; }
        public int Id_mugalim { get; set; }
        public int Id_okushy { get; set; }
    
        public virtual Ata_analar Ata_analar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jurnal> Jurnal { get; set; }
        public virtual Mugalimder Mugalimder { get; set; }
        public virtual Okushylar Okushylar { get; set; }
    }
}
