//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luck.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mektep_DBEntities : DbContext
    {
        public Mektep_DBEntities()
            : base("name=Mektep_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Ata_analar> Ata_analar { get; set; }
        public virtual DbSet<Jurnal> Jurnal { get; set; }
        public virtual DbSet<Mektepter> Mektepter { get; set; }
        public virtual DbSet<Meml_kyzmetker> Meml_kyzmetker { get; set; }
        public virtual DbSet<Mugalimder> Mugalimder { get; set; }
        public virtual DbSet<Okushylar> Okushylar { get; set; }
        public virtual DbSet<Pander> Pander { get; set; }
        public virtual DbSet<Register> Register { get; set; }
        public virtual DbSet<Sabak_kestesi> Sabak_kestesi { get; set; }
        public virtual DbSet<Synyptar> Synyptar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Events> Events { get; set; }
    }
}
